### ISSUE TITLE
iact3: command not found

### ISSUE THREAD

**Issue by hugsun** [aliyun/alibabacloud-ros-tool-iact3#44]
system env: x86_64 GNU/Linux
python version: 3.9

when i install iact3 with `pip install -t . alibabacloud-ros-iact3==0.1.8`
then run cmd `iact3`, show 
```
bash: iact3: command not found
```
it;s seem like `setup.py` 
```
...
scripts=["bin/iact3"]
...
```
the package covers the script `bin/iact3`

**Comment by xiao201208** [comment]
fix in version 0.1.9
